### ISSUE TITLE
USER STORY: As a Site User I can create an account so that I can post book reviews and comment on other users' reviews

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#1]
EPIC: Account creation

As a **Site User** I can **create an account** so that **I can post book reviews and comment on other users' reviews**.

**Acceptance Criteria**

- [x] User can click on register button to create an account
- [x] User can enter preferred username, email address, and password to create an account
- [x] When logged in, user can post book reviews and leave comments
- [x] When logged in, user can edit their own book reviews and their own comments

**Tasks**

- [x] Add registration button on navbar
- [x] Add registration page
- [x] Validate registration form and handle errors
- [x] Test account creation functionality
