### ISSUE TITLE
USER STORY: As a Site User I can visit the about page so that I can read about the purpose of the website

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#10]
EPIC: About page

As a **Site User** I can **visit the about page** so that **I can read about the purpose of the website**.

**Acceptance Criteria**

- [x] User can access the about page and see the description of the website

**Tasks**

- [x] Design about page user interface
- [ ] Test about page display and functionality
