### ISSUE TITLE
USER STORY: As a Site User I can fill out and submit a feedback form on the about page so that I can make suggestions to the site owner

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#11]
EPIC: About page

As a **Site User** I can **fill out and submit a feedback form on the about page** so that **I can make suggestions to the site owner**.

**Acceptance Criteria**

- [x] User can complete and submit a feedback form to the site owner

**Tasks**

- [x] Design feedback form
- [x] Validate feedback form and handle errors
- [x] Test feedback form functionality
