### ISSUE TITLE
USER STORY: As a Site User I can like a book review and comments so that I can show my positive reaction

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#13]
EPIC: Leave likes

As a **Site User** I can **like a book review and comments** so that **I can show my positive reaction**.

**Acceptance Criteria**

- [ ] When logged in, user can like book reviews and comments

**Tasks**

- [ ] Implement like button with icon
- [ ] Test like button functionality
