### ISSUE TITLE
USER STORY: As a Site User I can apply filters so that I can search book reviews per my preference

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#14]
EPIC: Filtering

As a **Site User** I can **apply filters** so that **I can search book reviews per my preference**.

**Acceptance Criteria**

- [ ] When logged in, user can filter book reviews by date of publish, book author, rating, and/or genre

**Tasks**

- [ ] Implement filtering feature
- [ ] Test filtering functionality
