### ISSUE TITLE
USER STORY: As a Site Owner I can advertise book club's book for the month on the home page so that users can see and decide to participate

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#15]
EPIC: Book club

As a **Site Owner** I can **advertise book club's book for the month on the home page** so that **users can see and decide to participate**.

**Acceptance Criteria**

- [ ] When logged in, owner can provide details of the book for the monthly book club in the admin panel
- [ ] This can be advertised on the home page for promotion and visibility

**Tasks**

- [ ] Design book club section on home page
- [ ] Add book club button on navbar
- [ ] Add book club page
- [ ] Test book club section and page functionality
