### ISSUE TITLE
USER STORY: As a Site User I can see the details of the book of this month's book club so that I can decide to participate

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#16]
EPIC: Book club

As a **Site User** I can **see the details of the book of this month's book club** so that **I can decide to participate**.

**Acceptance Criteria**

- [ ] User can read the information on what to read for the next book club meeting
- [ ] User can see how many other users have decided to participate
- [ ] When logged in, user can click on join button to participate

**Tasks**

- [ ] Design book club section on home page
- [ ] Add book club button on navbar
- [ ] Add book club page
- [ ] Display number of participants
- [ ] Test book club section and page functionality
