### ISSUE TITLE
USER STORY: As a Site User I can request to start my own book club so that I can meet like-minded users

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#17]
EPIC: Book club

As a **Site User** I can **request to start my own book club** so that **I can meet like-minded users**.

**Acceptance Criteria**

- [ ] Details on how to start a new book club are available on the book club page
- [ ] When logged in, user can complete a book club request form and submit for the site owner's review and approval

**Tasks**

- [ ] Add new book club request form on book club page
- [ ] Test book club request form functionality
