### ISSUE TITLE
USER STORY: As a Site Owner I can review new book club requests from users so that I can accept or reject them

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#18]
EPIC: Book club

As a **Site Owner** I can **review new book club requests from users** so that **I can accept or reject them**.

**Acceptance Criteria**

- [ ] A list of new book club requests can be viewed in the admin panel for accepting or rejecting
- [ ] A message to the user who submitted the request will be sent via email as to whether their request is accepted or rejected

**Tasks**

- [ ] Enable buttons for accepting or rejecting book club requests
- [ ] Implement message feature
- [ ] Test buttons and message functionalities
