### ISSUE TITLE
USER STORY: As a Site User I can post a review of a book so that I can share my thoughts and opinions with other users

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#2]
EPIC: Post book reviews

As a **Site User** I can **post a review of a book** so that **I can share my thoughts and opinions with other users**.

**Acceptance Criteria**

- [x] When logged in, user can click on a button to post a new book review
- [x] Then user can enter the cover photo, title, author, blurb, and genre of the book, as well as their rating out of 5 stars and their review
- [x] User can click publish to post book review, or save to drafts and finish it later
- [x] User can edit a published post

**Tasks**

- [x] Add a post a book review button
- [x] Implement a book review form with required fields
- [x] Add publish and save to drafts buttons
- [x] Validate book review form and handle errors
- [x] Add edit button on a published post
- [x] Test book review functionality
