### ISSUE TITLE
USER STORY: As a Site User I can leave comments so that I can share my thoughts and opinions of a book review with the reviewer

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#3]
EPIC: Leave comments

As a **Site User** I can **leave comments** so that **I can share my thoughts and opinions of a book review with the reviewer**.

**Acceptance Criteria**

- [x] When logged in, user can leave a comment under a book review

**Tasks**

- [x] Implement comment feature
- [x] Display number of comments under a book review
- [x] Test comment functionality
