### ISSUE TITLE
USER STORY: As a Site User I can visit my profile page so that I can see all my published book reviews and drafts, as well as update my profile photo and bio

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#6]
EPIC: Profile page

As a **Site User** I can **visit my profile page** so that **I can see all my published book reviews and drafts, as well as update my profile photo and bio**.

**Acceptance Criteria**

- [x] When logged in, user can access their profile page and see their published book reviews and drafts in decsending order by date of publish/update
- [x] User can update their profile photo and bio

**Tasks**

- [x] Add my profile page button on navbar
- [x] Link usernames to profile page as access point
- [x] Implement profile page with profile photo and bio sections
- [x] Test profile page functionality
