### ISSUE TITLE
USER STORY: As a Site User I can visit other user's profile page so that I can see all their published books reviews, as well as their profile photo and bio

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#7]
EPIC: Profile page

As a **Site User** I can **visit other user's profile page** so that **I can see all their published books reviews, as well as their profile photo and bio**.

**Acceptance Criteria**

- [x] User can access another user's profile page and see that user's published book reviews in descending order by date of publish/update
- [x] User can see the other user's profile photo and bio

**Tasks**

- [x] Link usernames to profile page as access point
- [x] Implement profile page with profile photo and bio sections
- [x] Test profile page functionality
