### ISSUE TITLE
USER STORY: As a Site User I can visit the home page so that I can see the most recent published book reviews by me or other users

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#8]
EPIC: Home page

As a **Site User** I can **visit the home page** so that **I can see the most recent published book reviews by me or other users**.

**Acceptance Criteria**

- [x] Home page displays the most recent pusblished book reviews in descending order by date of publish
- [x] Each book review displays the book cover, title, author, genre, and the reviewer's rating
- [x] Home page displays a maximum of six book reviews per page
- [x] Home page is paginated

**Tasks**

- [x] Add home page button on navbar
- [x] Link website logo to home page
- [x] Design home page user interface
- [x] Paginate home page
- [x] Test home page functionality
