### ISSUE TITLE
USER STORY: As a Site Owner I can edit the about page so that I can describe the purpose of my website

### ISSUE THREAD

**Issue by marcgithub23** [marcgithub23/pp4-reads-reviews#9]
EPIC: About page

As a **Site Owner** I can **edit the about page** so that **I can describe the purpose of my website**.

**Acceptance Criteria**

- [x] When logged in, I can edit the description of my website in the admin panel

**Tasks**

- [x] Implement about page in admin panel
- [x] Test edit about page functionality
